--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4
-- Dumped by pg_dump version 16.4

-- Started on 2025-05-04 16:36:16

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5 (class 2615 OID 33391)
-- Name: insurance; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA insurance;


ALTER SCHEMA insurance OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 33393)
-- Name: category_insurances; Type: TABLE; Schema: insurance; Owner: postgres
--

CREATE TABLE insurance.category_insurances (
    category_id integer NOT NULL,
    category_name character varying(100) NOT NULL,
    description text,
    base_rate numeric(10,2)
);


ALTER TABLE insurance.category_insurances OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 33392)
-- Name: category_insurances_category_id_seq; Type: SEQUENCE; Schema: insurance; Owner: postgres
--

ALTER TABLE insurance.category_insurances ALTER COLUMN category_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME insurance.category_insurances_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 33401)
-- Name: clients; Type: TABLE; Schema: insurance; Owner: postgres
--

CREATE TABLE insurance.clients (
    client_id integer NOT NULL,
    full_name character varying(100) NOT NULL,
    address character varying(200),
    phone_number character varying(20),
    email character varying(100),
    birth_date date NOT NULL,
    passport_data character varying(50)
);


ALTER TABLE insurance.clients OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 33400)
-- Name: clients_client_id_seq; Type: SEQUENCE; Schema: insurance; Owner: postgres
--

ALTER TABLE insurance.clients ALTER COLUMN client_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME insurance.clients_client_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 33411)
-- Name: employees; Type: TABLE; Schema: insurance; Owner: postgres
--

CREATE TABLE insurance.employees (
    employee_id integer NOT NULL,
    full_name character varying(100) NOT NULL,
    "position" character varying(100),
    phone_number character varying(20),
    email character varying(100),
    hire_date date NOT NULL
);


ALTER TABLE insurance.employees OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 33410)
-- Name: employees_employee_id_seq; Type: SEQUENCE; Schema: insurance; Owner: postgres
--

ALTER TABLE insurance.employees ALTER COLUMN employee_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME insurance.employees_employee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 33477)
-- Name: insurance_claims; Type: TABLE; Schema: insurance; Owner: postgres
--

CREATE TABLE insurance.insurance_claims (
    claim_id integer NOT NULL,
    claim_number character varying(50) NOT NULL,
    policy_event_id integer NOT NULL,
    claim_date date NOT NULL,
    description text,
    requested_amount numeric(15,2) NOT NULL,
    approved_amount numeric(15,2),
    status character varying(50) DEFAULT 'pending'::character varying,
    processed_by integer,
    processed_at timestamp without time zone
);


ALTER TABLE insurance.insurance_claims OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 33476)
-- Name: insurance_claims_claim_id_seq; Type: SEQUENCE; Schema: insurance; Owner: postgres
--

ALTER TABLE insurance.insurance_claims ALTER COLUMN claim_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME insurance.insurance_claims_claim_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 33419)
-- Name: insurance_policies; Type: TABLE; Schema: insurance; Owner: postgres
--

CREATE TABLE insurance.insurance_policies (
    policy_id integer NOT NULL,
    policy_number character varying(50) NOT NULL,
    client_id integer NOT NULL,
    category_id integer NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    insurance_amount numeric(15,2) NOT NULL,
    monthly_payment numeric(15,2) NOT NULL,
    status character varying(50) DEFAULT 'active'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE insurance.insurance_policies OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 33418)
-- Name: insurance_policies_policy_id_seq; Type: SEQUENCE; Schema: insurance; Owner: postgres
--

ALTER TABLE insurance.insurance_policies ALTER COLUMN policy_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME insurance.insurance_policies_policy_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 33441)
-- Name: insured_events; Type: TABLE; Schema: insurance; Owner: postgres
--

CREATE TABLE insurance.insured_events (
    event_id integer NOT NULL,
    event_name character varying(100) NOT NULL,
    description text,
    status character varying(50) DEFAULT 'active'::character varying,
    category_id integer NOT NULL,
    coverage_percentage numeric(5,2) NOT NULL,
    probability numeric(5,2) NOT NULL
);


ALTER TABLE insurance.insured_events OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 33440)
-- Name: insured_events_event_id_seq; Type: SEQUENCE; Schema: insurance; Owner: postgres
--

ALTER TABLE insurance.insured_events ALTER COLUMN event_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME insurance.insured_events_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 33500)
-- Name: payments; Type: TABLE; Schema: insurance; Owner: postgres
--

CREATE TABLE insurance.payments (
    payment_id integer NOT NULL,
    payment_number character varying(50) NOT NULL,
    client_id integer NOT NULL,
    policy_id integer,
    claim_id integer,
    amount numeric(15,2) NOT NULL,
    payment_date date NOT NULL,
    payment_type character varying(50) NOT NULL,
    status character varying(50) NOT NULL
);


ALTER TABLE insurance.payments OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 33499)
-- Name: payments_payment_id_seq; Type: SEQUENCE; Schema: insurance; Owner: postgres
--

ALTER TABLE insurance.payments ALTER COLUMN payment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME insurance.payments_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 33456)
-- Name: policy_events; Type: TABLE; Schema: insurance; Owner: postgres
--

CREATE TABLE insurance.policy_events (
    policy_event_id integer NOT NULL,
    policy_id integer NOT NULL,
    event_id integer NOT NULL,
    event_date date NOT NULL,
    status character varying(50) DEFAULT 'pending'::character varying,
    description text
);


ALTER TABLE insurance.policy_events OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 33455)
-- Name: policy_events_policy_event_id_seq; Type: SEQUENCE; Schema: insurance; Owner: postgres
--

ALTER TABLE insurance.policy_events ALTER COLUMN policy_event_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME insurance.policy_events_policy_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 33526)
-- Name: roles; Type: TABLE; Schema: insurance; Owner: postgres
--

CREATE TABLE insurance.roles (
    role_id integer NOT NULL,
    role_name character varying(50) NOT NULL,
    access_rights character varying(255)
);


ALTER TABLE insurance.roles OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 33525)
-- Name: roles_role_id_seq; Type: SEQUENCE; Schema: insurance; Owner: postgres
--

ALTER TABLE insurance.roles ALTER COLUMN role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME insurance.roles_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 33534)
-- Name: users; Type: TABLE; Schema: insurance; Owner: postgres
--

CREATE TABLE insurance.users (
    user_id integer NOT NULL,
    username character varying(50) NOT NULL,
    password_hash character varying(255) NOT NULL,
    role_id integer,
    client_id integer,
    employee_id integer,
    CONSTRAINT chk_user_type CHECK ((((client_id IS NOT NULL) AND (employee_id IS NULL)) OR ((client_id IS NULL) AND (employee_id IS NOT NULL)) OR ((client_id IS NULL) AND (employee_id IS NULL))))
);


ALTER TABLE insurance.users OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 33533)
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: insurance; Owner: postgres
--

ALTER TABLE insurance.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME insurance.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4895 (class 0 OID 33393)
-- Dependencies: 216
-- Data for Name: category_insurances; Type: TABLE DATA; Schema: insurance; Owner: postgres
--

COPY insurance.category_insurances (category_id, category_name, description, base_rate) FROM stdin;
\.


--
-- TOC entry 4897 (class 0 OID 33401)
-- Dependencies: 218
-- Data for Name: clients; Type: TABLE DATA; Schema: insurance; Owner: postgres
--

COPY insurance.clients (client_id, full_name, address, phone_number, email, birth_date, passport_data) FROM stdin;
\.


--
-- TOC entry 4899 (class 0 OID 33411)
-- Dependencies: 220
-- Data for Name: employees; Type: TABLE DATA; Schema: insurance; Owner: postgres
--

COPY insurance.employees (employee_id, full_name, "position", phone_number, email, hire_date) FROM stdin;
\.


--
-- TOC entry 4907 (class 0 OID 33477)
-- Dependencies: 228
-- Data for Name: insurance_claims; Type: TABLE DATA; Schema: insurance; Owner: postgres
--

COPY insurance.insurance_claims (claim_id, claim_number, policy_event_id, claim_date, description, requested_amount, approved_amount, status, processed_by, processed_at) FROM stdin;
\.


--
-- TOC entry 4901 (class 0 OID 33419)
-- Dependencies: 222
-- Data for Name: insurance_policies; Type: TABLE DATA; Schema: insurance; Owner: postgres
--

COPY insurance.insurance_policies (policy_id, policy_number, client_id, category_id, start_date, end_date, insurance_amount, monthly_payment, status, created_at) FROM stdin;
\.


--
-- TOC entry 4903 (class 0 OID 33441)
-- Dependencies: 224
-- Data for Name: insured_events; Type: TABLE DATA; Schema: insurance; Owner: postgres
--

COPY insurance.insured_events (event_id, event_name, description, status, category_id, coverage_percentage, probability) FROM stdin;
\.


--
-- TOC entry 4909 (class 0 OID 33500)
-- Dependencies: 230
-- Data for Name: payments; Type: TABLE DATA; Schema: insurance; Owner: postgres
--

COPY insurance.payments (payment_id, payment_number, client_id, policy_id, claim_id, amount, payment_date, payment_type, status) FROM stdin;
\.


--
-- TOC entry 4905 (class 0 OID 33456)
-- Dependencies: 226
-- Data for Name: policy_events; Type: TABLE DATA; Schema: insurance; Owner: postgres
--

COPY insurance.policy_events (policy_event_id, policy_id, event_id, event_date, status, description) FROM stdin;
\.


--
-- TOC entry 4911 (class 0 OID 33526)
-- Dependencies: 232
-- Data for Name: roles; Type: TABLE DATA; Schema: insurance; Owner: postgres
--

COPY insurance.roles (role_id, role_name, access_rights) FROM stdin;
\.


--
-- TOC entry 4913 (class 0 OID 33534)
-- Dependencies: 234
-- Data for Name: users; Type: TABLE DATA; Schema: insurance; Owner: postgres
--

COPY insurance.users (user_id, username, password_hash, role_id, client_id, employee_id) FROM stdin;
\.


--
-- TOC entry 4919 (class 0 OID 0)
-- Dependencies: 215
-- Name: category_insurances_category_id_seq; Type: SEQUENCE SET; Schema: insurance; Owner: postgres
--

SELECT pg_catalog.setval('insurance.category_insurances_category_id_seq', 1, false);


--
-- TOC entry 4920 (class 0 OID 0)
-- Dependencies: 217
-- Name: clients_client_id_seq; Type: SEQUENCE SET; Schema: insurance; Owner: postgres
--

SELECT pg_catalog.setval('insurance.clients_client_id_seq', 1, false);


--
-- TOC entry 4921 (class 0 OID 0)
-- Dependencies: 219
-- Name: employees_employee_id_seq; Type: SEQUENCE SET; Schema: insurance; Owner: postgres
--

SELECT pg_catalog.setval('insurance.employees_employee_id_seq', 1, false);


--
-- TOC entry 4922 (class 0 OID 0)
-- Dependencies: 227
-- Name: insurance_claims_claim_id_seq; Type: SEQUENCE SET; Schema: insurance; Owner: postgres
--

SELECT pg_catalog.setval('insurance.insurance_claims_claim_id_seq', 1, false);


--
-- TOC entry 4923 (class 0 OID 0)
-- Dependencies: 221
-- Name: insurance_policies_policy_id_seq; Type: SEQUENCE SET; Schema: insurance; Owner: postgres
--

SELECT pg_catalog.setval('insurance.insurance_policies_policy_id_seq', 1, false);


--
-- TOC entry 4924 (class 0 OID 0)
-- Dependencies: 223
-- Name: insured_events_event_id_seq; Type: SEQUENCE SET; Schema: insurance; Owner: postgres
--

SELECT pg_catalog.setval('insurance.insured_events_event_id_seq', 1, false);


--
-- TOC entry 4925 (class 0 OID 0)
-- Dependencies: 229
-- Name: payments_payment_id_seq; Type: SEQUENCE SET; Schema: insurance; Owner: postgres
--

SELECT pg_catalog.setval('insurance.payments_payment_id_seq', 1, false);


--
-- TOC entry 4926 (class 0 OID 0)
-- Dependencies: 225
-- Name: policy_events_policy_event_id_seq; Type: SEQUENCE SET; Schema: insurance; Owner: postgres
--

SELECT pg_catalog.setval('insurance.policy_events_policy_event_id_seq', 1, false);


--
-- TOC entry 4927 (class 0 OID 0)
-- Dependencies: 231
-- Name: roles_role_id_seq; Type: SEQUENCE SET; Schema: insurance; Owner: postgres
--

SELECT pg_catalog.setval('insurance.roles_role_id_seq', 1, false);


--
-- TOC entry 4928 (class 0 OID 0)
-- Dependencies: 233
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: insurance; Owner: postgres
--

SELECT pg_catalog.setval('insurance.users_user_id_seq', 1, false);


--
-- TOC entry 4686 (class 2606 OID 33399)
-- Name: category_insurances category_insurances_pkey; Type: CONSTRAINT; Schema: insurance; Owner: postgres
--

ALTER TABLE ONLY insurance.category_insurances
    ADD CONSTRAINT category_insurances_pkey PRIMARY KEY (category_id);


--
-- TOC entry 4688 (class 2606 OID 33407)
-- Name: clients clients_email_key; Type: CONSTRAINT; Schema: insurance; Owner: postgres
--

ALTER TABLE ONLY insurance.clients
    ADD CONSTRAINT clients_email_key UNIQUE (email);


--
-- TOC entry 4690 (class 2606 OID 33409)
-- Name: clients clients_passport_data_key; Type: CONSTRAINT; Schema: insurance; Owner: postgres
--

ALTER TABLE ONLY insurance.clients
    ADD CONSTRAINT clients_passport_data_key UNIQUE (passport_data);


--
-- TOC entry 4692 (class 2606 OID 33405)
-- Name: clients clients_pkey; Type: CONSTRAINT; Schema: insurance; Owner: postgres
--

ALTER TABLE ONLY insurance.clients
    ADD CONSTRAINT clients_pkey PRIMARY KEY (client_id);


--
-- TOC entry 4694 (class 2606 OID 33417)
-- Name: employees employees_email_key; Type: CONSTRAINT; Schema: insurance; Owner: postgres
--

ALTER TABLE ONLY insurance.employees
    ADD CONSTRAINT employees_email_key UNIQUE (email);


--
-- TOC entry 4696 (class 2606 OID 33415)
-- Name: employees employees_pkey; Type: CONSTRAINT; Schema: insurance; Owner: postgres
--

ALTER TABLE ONLY insurance.employees
    ADD CONSTRAINT employees_pkey PRIMARY KEY (employee_id);


--
-- TOC entry 4713 (class 2606 OID 33486)
-- Name: insurance_claims insurance_claims_claim_number_key; Type: CONSTRAINT; Schema: insurance; Owner: postgres
--

ALTER TABLE ONLY insurance.insurance_claims
    ADD CONSTRAINT insurance_claims_claim_number_key UNIQUE (claim_number);


--
-- TOC entry 4715 (class 2606 OID 33484)
-- Name: insurance_claims insurance_claims_pkey; Type: CONSTRAINT; Schema: insurance; Owner: postgres
--

ALTER TABLE ONLY insurance.insurance_claims
    ADD CONSTRAINT insurance_claims_pkey PRIMARY KEY (claim_id);


--
-- TOC entry 4700 (class 2606 OID 33425)
-- Name: insurance_policies insurance_policies_pkey; Type: CONSTRAINT; Schema: insurance; Owner: postgres
--

ALTER TABLE ONLY insurance.insurance_policies
    ADD CONSTRAINT insurance_policies_pkey PRIMARY KEY (policy_id);


--
-- TOC entry 4702 (class 2606 OID 33427)
-- Name: insurance_policies insurance_policies_policy_number_key; Type: CONSTRAINT; Schema: insurance; Owner: postgres
--

ALTER TABLE ONLY insurance.insurance_policies
    ADD CONSTRAINT insurance_policies_policy_number_key UNIQUE (policy_number);


--
-- TOC entry 4705 (class 2606 OID 33448)
-- Name: insured_events insured_events_pkey; Type: CONSTRAINT; Schema: insurance; Owner: postgres
--

ALTER TABLE ONLY insurance.insured_events
    ADD CONSTRAINT insured_events_pkey PRIMARY KEY (event_id);


--
-- TOC entry 4720 (class 2606 OID 33506)
-- Name: payments payments_payment_number_key; Type: CONSTRAINT; Schema: insurance; Owner: postgres
--

ALTER TABLE ONLY insurance.payments
    ADD CONSTRAINT payments_payment_number_key UNIQUE (payment_number);


--
-- TOC entry 4722 (class 2606 OID 33504)
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: insurance; Owner: postgres
--

ALTER TABLE ONLY insurance.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (payment_id);


--
-- TOC entry 4709 (class 2606 OID 33463)
-- Name: policy_events policy_events_pkey; Type: CONSTRAINT; Schema: insurance; Owner: postgres
--

ALTER TABLE ONLY insurance.policy_events
    ADD CONSTRAINT policy_events_pkey PRIMARY KEY (policy_event_id);


--
-- TOC entry 4724 (class 2606 OID 33530)
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: insurance; Owner: postgres
--

ALTER TABLE ONLY insurance.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (role_id);


--
-- TOC entry 4726 (class 2606 OID 33532)
-- Name: roles roles_role_name_key; Type: CONSTRAINT; Schema: insurance; Owner: postgres
--

ALTER TABLE ONLY insurance.roles
    ADD CONSTRAINT roles_role_name_key UNIQUE (role_name);


--
-- TOC entry 4731 (class 2606 OID 33543)
-- Name: users users_client_id_key; Type: CONSTRAINT; Schema: insurance; Owner: postgres
--

ALTER TABLE ONLY insurance.users
    ADD CONSTRAINT users_client_id_key UNIQUE (client_id);


--
-- TOC entry 4733 (class 2606 OID 33545)
-- Name: users users_employee_id_key; Type: CONSTRAINT; Schema: insurance; Owner: postgres
--

ALTER TABLE ONLY insurance.users
    ADD CONSTRAINT users_employee_id_key UNIQUE (employee_id);


--
-- TOC entry 4735 (class 2606 OID 33539)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: insurance; Owner: postgres
--

ALTER TABLE ONLY insurance.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- TOC entry 4737 (class 2606 OID 33541)
-- Name: users users_username_key; Type: CONSTRAINT; Schema: insurance; Owner: postgres
--

ALTER TABLE ONLY insurance.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- TOC entry 4710 (class 1259 OID 33497)
-- Name: idx_claims_policyevent_id; Type: INDEX; Schema: insurance; Owner: postgres
--

CREATE INDEX idx_claims_policyevent_id ON insurance.insurance_claims USING btree (policy_event_id);


--
-- TOC entry 4711 (class 1259 OID 33498)
-- Name: idx_claims_processedby_id; Type: INDEX; Schema: insurance; Owner: postgres
--

CREATE INDEX idx_claims_processedby_id ON insurance.insurance_claims USING btree (processed_by);


--
-- TOC entry 4703 (class 1259 OID 33454)
-- Name: idx_events_category_id; Type: INDEX; Schema: insurance; Owner: postgres
--

CREATE INDEX idx_events_category_id ON insurance.insured_events USING btree (category_id);


--
-- TOC entry 4716 (class 1259 OID 33524)
-- Name: idx_payments_claim_id; Type: INDEX; Schema: insurance; Owner: postgres
--

CREATE INDEX idx_payments_claim_id ON insurance.payments USING btree (claim_id);


--
-- TOC entry 4717 (class 1259 OID 33522)
-- Name: idx_payments_client_id; Type: INDEX; Schema: insurance; Owner: postgres
--

CREATE INDEX idx_payments_client_id ON insurance.payments USING btree (client_id);


--
-- TOC entry 4718 (class 1259 OID 33523)
-- Name: idx_payments_policy_id; Type: INDEX; Schema: insurance; Owner: postgres
--

CREATE INDEX idx_payments_policy_id ON insurance.payments USING btree (policy_id);


--
-- TOC entry 4697 (class 1259 OID 33439)
-- Name: idx_policies_category_id; Type: INDEX; Schema: insurance; Owner: postgres
--

CREATE INDEX idx_policies_category_id ON insurance.insurance_policies USING btree (category_id);


--
-- TOC entry 4698 (class 1259 OID 33438)
-- Name: idx_policies_client_id; Type: INDEX; Schema: insurance; Owner: postgres
--

CREATE INDEX idx_policies_client_id ON insurance.insurance_policies USING btree (client_id);


--
-- TOC entry 4706 (class 1259 OID 33475)
-- Name: idx_policyevents_event_id; Type: INDEX; Schema: insurance; Owner: postgres
--

CREATE INDEX idx_policyevents_event_id ON insurance.policy_events USING btree (event_id);


--
-- TOC entry 4707 (class 1259 OID 33474)
-- Name: idx_policyevents_policy_id; Type: INDEX; Schema: insurance; Owner: postgres
--

CREATE INDEX idx_policyevents_policy_id ON insurance.policy_events USING btree (policy_id);


--
-- TOC entry 4727 (class 1259 OID 33562)
-- Name: idx_users_client_id; Type: INDEX; Schema: insurance; Owner: postgres
--

CREATE INDEX idx_users_client_id ON insurance.users USING btree (client_id);


--
-- TOC entry 4728 (class 1259 OID 33563)
-- Name: idx_users_employee_id; Type: INDEX; Schema: insurance; Owner: postgres
--

CREATE INDEX idx_users_employee_id ON insurance.users USING btree (employee_id);


--
-- TOC entry 4729 (class 1259 OID 33561)
-- Name: idx_users_role_id; Type: INDEX; Schema: insurance; Owner: postgres
--

CREATE INDEX idx_users_role_id ON insurance.users USING btree (role_id);


--
-- TOC entry 4743 (class 2606 OID 33492)
-- Name: insurance_claims fk_claims_employee; Type: FK CONSTRAINT; Schema: insurance; Owner: postgres
--

ALTER TABLE ONLY insurance.insurance_claims
    ADD CONSTRAINT fk_claims_employee FOREIGN KEY (processed_by) REFERENCES insurance.employees(employee_id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- TOC entry 4744 (class 2606 OID 33487)
-- Name: insurance_claims fk_claims_policyevent; Type: FK CONSTRAINT; Schema: insurance; Owner: postgres
--

ALTER TABLE ONLY insurance.insurance_claims
    ADD CONSTRAINT fk_claims_policyevent FOREIGN KEY (policy_event_id) REFERENCES insurance.policy_events(policy_event_id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 4740 (class 2606 OID 33449)
-- Name: insured_events fk_events_category; Type: FK CONSTRAINT; Schema: insurance; Owner: postgres
--

ALTER TABLE ONLY insurance.insured_events
    ADD CONSTRAINT fk_events_category FOREIGN KEY (category_id) REFERENCES insurance.category_insurances(category_id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 4745 (class 2606 OID 33517)
-- Name: payments fk_payments_claim; Type: FK CONSTRAINT; Schema: insurance; Owner: postgres
--

ALTER TABLE ONLY insurance.payments
    ADD CONSTRAINT fk_payments_claim FOREIGN KEY (claim_id) REFERENCES insurance.insurance_claims(claim_id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- TOC entry 4746 (class 2606 OID 33507)
-- Name: payments fk_payments_client; Type: FK CONSTRAINT; Schema: insurance; Owner: postgres
--

ALTER TABLE ONLY insurance.payments
    ADD CONSTRAINT fk_payments_client FOREIGN KEY (client_id) REFERENCES insurance.clients(client_id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 4747 (class 2606 OID 33512)
-- Name: payments fk_payments_policy; Type: FK CONSTRAINT; Schema: insurance; Owner: postgres
--

ALTER TABLE ONLY insurance.payments
    ADD CONSTRAINT fk_payments_policy FOREIGN KEY (policy_id) REFERENCES insurance.insurance_policies(policy_id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- TOC entry 4738 (class 2606 OID 33433)
-- Name: insurance_policies fk_policies_category; Type: FK CONSTRAINT; Schema: insurance; Owner: postgres
--

ALTER TABLE ONLY insurance.insurance_policies
    ADD CONSTRAINT fk_policies_category FOREIGN KEY (category_id) REFERENCES insurance.category_insurances(category_id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 4739 (class 2606 OID 33428)
-- Name: insurance_policies fk_policies_client; Type: FK CONSTRAINT; Schema: insurance; Owner: postgres
--

ALTER TABLE ONLY insurance.insurance_policies
    ADD CONSTRAINT fk_policies_client FOREIGN KEY (client_id) REFERENCES insurance.clients(client_id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 4741 (class 2606 OID 33469)
-- Name: policy_events fk_policyevents_event; Type: FK CONSTRAINT; Schema: insurance; Owner: postgres
--

ALTER TABLE ONLY insurance.policy_events
    ADD CONSTRAINT fk_policyevents_event FOREIGN KEY (event_id) REFERENCES insurance.insured_events(event_id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 4742 (class 2606 OID 33464)
-- Name: policy_events fk_policyevents_policy; Type: FK CONSTRAINT; Schema: insurance; Owner: postgres
--

ALTER TABLE ONLY insurance.policy_events
    ADD CONSTRAINT fk_policyevents_policy FOREIGN KEY (policy_id) REFERENCES insurance.insurance_policies(policy_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4748 (class 2606 OID 33551)
-- Name: users fk_users_client; Type: FK CONSTRAINT; Schema: insurance; Owner: postgres
--

ALTER TABLE ONLY insurance.users
    ADD CONSTRAINT fk_users_client FOREIGN KEY (client_id) REFERENCES insurance.clients(client_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4749 (class 2606 OID 33556)
-- Name: users fk_users_employee; Type: FK CONSTRAINT; Schema: insurance; Owner: postgres
--

ALTER TABLE ONLY insurance.users
    ADD CONSTRAINT fk_users_employee FOREIGN KEY (employee_id) REFERENCES insurance.employees(employee_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4750 (class 2606 OID 33546)
-- Name: users fk_users_role; Type: FK CONSTRAINT; Schema: insurance; Owner: postgres
--

ALTER TABLE ONLY insurance.users
    ADD CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES insurance.roles(role_id) ON UPDATE CASCADE ON DELETE SET NULL;


-- Completed on 2025-05-04 16:36:16

--
-- PostgreSQL database dump complete
--

